### ISSUE TITLE
Crash caused by D2ExcelPlus

### ISSUE THREAD

**Issue by NxHunter** [Cjreek/D2ExcelPlus#1]
Hey, 

Just attempted to change the Velocity and Run values for skeleton1 when I started to encounter this error. It also seemed to be happening when attempting to change other basic values when they had previously been editable before.

I've managed to safely edit both of the values with Google Sheets & Notepad ++
It seems that only the D2ExcelPlus is causing me some issues at the moment, unsure of cause and just wanted to raise awareness.

Below are the files, you'll be able to see the diffs. 

### Edited File [MonStats.txt](https://github.com/Cjreek/D2ExcelPlus/files/2897521/MonStats.txt)

![image](https://user-images.githubusercontent.com/47932267/53294447-220ca700-37df-11e9-801d-b3716f81d55f.png)

**Comment by Cjreek** [comment]
Issue is fixed. New version where this bug is fixed + Undo/Redo and multiselect feature is available here
https://drive.google.com/open?id=1GZIb-j8fGEd2a70EU7jvF967OvgeHDeV
 or in this repository (source)
