### ISSUE TITLE
Build opensource app? guide

### ISSUE THREAD

**Issue by KDGNOR** [Cjreek/D2ExcelPlus#2]
On Windows
or on Linux
or on MacOSX

**Comment by Cjreek** [comment]
I'm not sure what exactly your question is.
D2ExcelPlus is built with Delphi (VCL). To build this yourself you need to download the Delphi Community Edition:
https://www.embarcadero.com/de/products/delphi/starter

VCL is a Windows-Only framework, so you can't compile this for Linux or MacOS without translating the code to the FMX framework or to another language.
