### ISSUE TITLE
Copy/Paste

### ISSUE THREAD

**Issue by Duits** [Cjreek/D2ExcelPlus#4]
If you want to Paste 1 value from 1 cell into multiple cells you have to copy that value from the same number of cells you wish to paste in.
For instance Copying 1 cell with a 0 will only allow to paste in 1 cell even if you select multiple to paste in simultaneously. 
So if you wanted to paste a column of 10 consecutive 0's you would have to first copy a column of 10 consecutive 0's.

**Comment by Cjreek** [comment]
Fixed. Now works like it does in Excel (allowing you to do what you described in the issue)
